version: '3.8'

services:
  financeai-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://financeai:${DB_PASSWORD}@db:5432/financeai
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
    restart: unless-stopped
    
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=financeai
      - POSTGRES_USER=financeai
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  financeai-frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - financeai-api
    restart: unless-stopped

volumes:
  postgres_data: